services:
  # CLient - Phaser game image
  client:
    build:
      context: $CLIENTDIR
      dockerfile: Dockerfile
    container_name: client
    hostname: client
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - primary-network
    ports:
      - "8081:8081"
    volumes:
    - ../client:/app