services:
  # Game - Phaser game image
  game:
    build:
      context: $GAMEDIR
      dockerfile: Dockerfile
    container_name: game
    hostname: game
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - primary-network
    ports:
      - "8081:8081"
    volumes:
    - ../game:/app